<?php

namespace Database\Seeders;

use App\Models\Customers;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $customers = [
            [
                'customer_code' => 'CUST-001',
                'customer_img' => null,
                'name' => 'AB CONSTRUCTION & SUPPLY',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-002',
                'customer_img' => null,
                'name' => 'AGR ENTERPRISE',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-003',
                'customer_img' => null,
                'name' => 'AGT TRUCKING /LOGISTICS',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-004',
                'customer_img' => null,
                'name' => 'AJ ADLAWAN CONSTRUCTION',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-005',
                'customer_img' => null,
                'name' => 'ALCIDOR LARIOSA',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-006',
                'customer_img' => null,
                'name' => 'ANTHILL - REVETMENT',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-007',
                'customer_img' => null,
                'name' => 'ANTHILL CONSTRUCTION',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-008',
                'customer_img' => null,
                'name' => 'APRIL JEAN OMANDAC',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-009',
                'customer_img' => null,
                'name' => 'ARNOLD PUZON',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-010',
                'customer_img' => null,
                'name' => 'AUTOTECH',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-011',
                'customer_img' => null,
                'name' => 'BIBU SQUARE',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-012',
                'customer_img' => null,
                'name' => 'BRIDGE DIGITAL TRANSFORMATION INC.',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-013',
                'customer_img' => null,
                'name' => 'CARLITO PATROMO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-014',
                'customer_img' => null,
                'name' => 'CARMEN ABATAYO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-015',
                'customer_img' => null,
                'name' => 'CENTER FOR BRIGHTER BEGINNINGS (CBB)',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-016',
                'customer_img' => null,
                'name' => 'CRES MARIE GALANG',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-017',
                'customer_img' => null,
                'name' => 'CRISTIN ESDRELON',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-018',
                'customer_img' => null,
                'name' => 'CRISTINA CONCHA',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-019',
                'customer_img' => null,
                'name' => 'DANECO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-020',
                'customer_img' => null,
                'name' => 'DANIEL CALPITO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-021',
                'customer_img' => null,
                'name' => 'DARWIN TAGUD',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-022',
                'customer_img' => null,
                'name' => 'DEAN FARELLE BESTUDIO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-023',
                'customer_img' => null,
                'name' => 'DGD MARINE PARK',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-024',
                'customer_img' => null,
                'name' => 'DMP FLOATING COTTAGE',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-025',
                'customer_img' => null,
                'name' => 'DURABLOC',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-026',
                'customer_img' => null,
                'name' => 'EDGAR REBUCAS',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-027',
                'customer_img' => null,
                'name' => 'EDGARDO CONCHA',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-028',
                'customer_img' => null,
                'name' => 'ENGR. PEDRO BALILI',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-029',
                'customer_img' => null,
                'name' => 'ENGR. ZOSIMO ROSALES',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-030',
                'customer_img' => null,
                'name' => 'FELIPE CALINGA',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-031',
                'customer_img' => null,
                'name' => 'FERDINAND GALANG - M5',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-032',
                'customer_img' => null,
                'name' => 'FERDINAND GALANG - M5 (HERMANA TRUCKING)',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-033',
                'customer_img' => null,
                'name' => 'FERNANDO FLORES',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-034',
                'customer_img' => null,
                'name' => 'FRITZ FLOYD AÑORA',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-035',
                'customer_img' => null,
                'name' => 'GALANG FARM',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-036',
                'customer_img' => null,
                'name' => 'GLEN ROLLORATA',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-037',
                'customer_img' => null,
                'name' => 'GLORIOUS OFFICE',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-038',
                'customer_img' => null,
                'name' => 'GT ENTERPRISE (PERSONAL)',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-039',
                'customer_img' => null,
                'name' => 'GT ENTERPRISE (TRUCKING)',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-040',
                'customer_img' => null,
                'name' => 'HOBBY PLUS',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-041',
                'customer_img' => null,
                'name' => 'INIGO TAOJO (HOUSE RENOVATION)',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-042',
                'customer_img' => null,
                'name' => 'JESSIE IBARRA',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-043',
                'customer_img' => null,
                'name' => 'JOHNLERY ARCENAL',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-044',
                'customer_img' => null,
                'name' => 'JOY GENON',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-045',
                'customer_img' => null,
                'name' => 'KANAWAY BUILDERS CORPORATION',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-046',
                'customer_img' => null,
                'name' => 'KANOFFEE',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-047',
                'customer_img' => null,
                'name' => 'LABIO CONCHA',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-048',
                'customer_img' => null,
                'name' => 'LESERIO A. LAGANG JR.',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-049',
                'customer_img' => null,
                'name' => 'LUCY URBANO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-050',
                'customer_img' => null,
                'name' => 'MABANGLO, ARTHUR',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-051',
                'customer_img' => null,
                'name' => 'MAER SUMMIT KONSTRUKT',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-052',
                'customer_img' => null,
                'name' => 'MARILOU RAMOS',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-053',
                'customer_img' => null,
                'name' => 'MARK CAÑAS',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-054',
                'customer_img' => null,
                'name' => 'MARK GULTIANO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-055',
                'customer_img' => null,
                'name' => 'MERIBETH BANTING',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-056',
                'customer_img' => null,
                'name' => 'MICHAEL EARL FERRER',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-057',
                'customer_img' => null,
                'name' => 'MINDANAMICS',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-058',
                'customer_img' => null,
                'name' => 'MMT CARRIER',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-059',
                'customer_img' => null,
                'name' => 'NOE B. TAOJO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-060',
                'customer_img' => null,
                'name' => 'PARAMINA-I',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-061',
                'customer_img' => null,
                'name' => 'PARAMINA-II',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-062',
                'customer_img' => null,
                'name' => 'POWER-UP',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-063',
                'customer_img' => null,
                'name' => 'RELIABUILD',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-064',
                'customer_img' => null,
                'name' => 'RENAN MACLA',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-065',
                'customer_img' => null,
                'name' => 'RIZAL MEMORIAL COLLEGE',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-066',
                'customer_img' => null,
                'name' => 'ROMEO GELI',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-067',
                'customer_img' => null,
                'name' => 'RONAND ELKIN LAO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-068',
                'customer_img' => null,
                'name' => 'ROWENA BELLO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-069',
                'customer_img' => null,
                'name' => 'RUFFY IAN SABINO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-070',
                'customer_img' => null,
                'name' => 'SERRY CABANSAG',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-071',
                'customer_img' => null,
                'name' => 'SHIELA MARIE LUCERO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-072',
                'customer_img' => null,
                'name' => 'STEWART TAOJO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-073',
                'customer_img' => null,
                'name' => 'TAGUM GOLF',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-074',
                'customer_img' => null,
                'name' => 'TOMY QUINTO',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-075',
                'customer_img' => null,
                'name' => 'TRN AUTO PARTS TRADING',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-076',
                'customer_img' => null,
                'name' => 'TRUINE',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-077',
                'customer_img' => null,
                'name' => 'ULTRA MEDICAL CLINIC',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_code' => 'CUST-078',
                'customer_img' => null,
                'name' => 'USI - FUELS',
                'email' => null,
                'contact_no' => null,
                'affiliated' => false,
                'isactive' => true,
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($customers as $customer) {
            Customers::create($customer);
        }
    }
}
