import {
  ActivityIcon,
  Archive,
  ArchiveRestore,
  ArchiveX,
  ArrowDownToDot,
  ArrowsUpFromLine,
  ArrowUpFromDot,
  BadgePercent,
  BaggageClaim,
  CircleSlash,
  ClipboardPlus,
  Cog,
  Container,
  CreditCard,
  Menu as DashboardMenu,
  Gift,
  GitPullRequestCreateArrow,
  Group as GroupOperations,
  LayoutGrid,
  LucideIcon,
  Package,
  Package2,
  PackageOpen,
  PackageSearch,
  PhilippinePeso,
  Ratio,
  Ruler,
  SendToBack,
  ShoppingBag,
  ShoppingCart,
  SquarePercent,
  StretchHorizontal,
  Undo2,
  Ungroup,
  User,
  Users2Icon,
  Wallet,
} from "lucide-react"
import { PAGE_ROUTES } from "@/config/page-routes"
import {
  PermissionType,
  ROLES_FEATURES_PERMISSIONS,
} from "@/config/roles-features-permissions-template"

export interface Submenu {
  href?: string
  label?: string
  active?: boolean
  icon?: LucideIcon
  allowedRoles?: string[]
  allowedFeatures?: string[]
  allowedPermissions?: readonly string[] | PermissionType[]
  allowedDepartments?: string[]
}

export interface Menu {
  href?: string
  label?: string
  active?: boolean
  icon?: LucideIcon
  submenus?: Submenu[]
  allowedRoles?: string[]
  allowedFeatures?: string[]
  allowedPermissions?: PermissionType[]
  allowedDepartments?: string[]
}

export interface Group {
  groupLabel?: string
  menus?: Menu[]
}

export function getMenuList(pathname: string): Group[] {
  const path = pathname.split("?")[0]

  const SALES_OFFICER = ROLES_FEATURES_PERMISSIONS.SALES_OFFICER
  const CASHIER = ROLES_FEATURES_PERMISSIONS.CASHIER
  const INVENTORY_MANAGER = ROLES_FEATURES_PERMISSIONS.INVENTORY_MANAGER
  const INVENTORY_OFFICER = ROLES_FEATURES_PERMISSIONS.INVENTORY_OFFICER
  const ADMINISTRATOR = ROLES_FEATURES_PERMISSIONS.ADMINISTRATOR
  const MERCHANDISER = ROLES_FEATURES_PERMISSIONS.MERCHANDISER
  const EVP = ROLES_FEATURES_PERMISSIONS.EVP
  const PURCHASING_AND_SALES_HEAD =
    ROLES_FEATURES_PERMISSIONS.PURCHASING_AND_SALES_HEAD
  const SUPERVISOR = ROLES_FEATURES_PERMISSIONS.SUPERVISOR
  const SUPER_ADMIN = ROLES_FEATURES_PERMISSIONS.SUPER_ADMIN

  return [
    {
      menus: [
        {
          href: PAGE_ROUTES.DASHBOARD_PAGE,
          label: "Menu",
          icon: DashboardMenu,
          allowedRoles: [
            SALES_OFFICER.role,
            CASHIER.role,
            INVENTORY_MANAGER.role,
            INVENTORY_OFFICER.role,
            PURCHASING_AND_SALES_HEAD.role,
            EVP.role,
            MERCHANDISER.role,
            ADMINISTRATOR.role,
            SUPERVISOR.role,
            SUPER_ADMIN.role,
          ],
          allowedFeatures: [
            "reports_and_analytics",
            "create_order",
            "customer_profile",
          ],
          submenus: [
            {
              href: PAGE_ROUTES.DASHBOARD_PAGE,
              label: "Dashboard",
              active: path === PAGE_ROUTES.DASHBOARD_PAGE,
              icon: LayoutGrid,
              allowedRoles: [
                SALES_OFFICER.role,
                CASHIER.role,
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                MERCHANDISER.role,
                ADMINISTRATOR.role,
                SUPERVISOR.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["reports_and_analytics"],
              allowedPermissions: [
                ...SALES_OFFICER.permissions.reports_and_analytics,
                ...CASHIER.permissions.reports_and_analytics,
                ...INVENTORY_MANAGER.permissions.reports_and_analytics,
                ...INVENTORY_OFFICER.permissions.reports_and_analytics,
                ...PURCHASING_AND_SALES_HEAD.permissions.reports_and_analytics,
                ...EVP.permissions.reports_and_analytics,
                ...MERCHANDISER.permissions.reports_and_analytics,
                ...ADMINISTRATOR.permissions.reports_and_analytics,
                ...SUPERVISOR.permissions.reports_and_analytics,
                ...SUPER_ADMIN.permissions.reports_and_analytics,
              ],
            },
            {
              href: PAGE_ROUTES.PRODUCTS_PAGE,
              label: "Products",
              active: path === PAGE_ROUTES.PRODUCTS_PAGE,
              icon: PackageSearch,
              allowedRoles: [SALES_OFFICER.role, SUPER_ADMIN.role],
              allowedFeatures: ["create_order"],
              allowedPermissions: [
                ...SALES_OFFICER.permissions.create_order,
                ...SUPER_ADMIN.permissions.create_order,
              ],
            },
            {
              href: PAGE_ROUTES.CREATE_ORDERS_PAGE,
              label: "Order Selection",
              active: path === PAGE_ROUTES.CREATE_ORDERS_PAGE,
              icon: ShoppingCart,
              allowedRoles: [SALES_OFFICER.role, SUPER_ADMIN.role],
              allowedFeatures: ["create_order"],
              allowedPermissions: [
                ...SALES_OFFICER.permissions.create_order,
                ...SUPER_ADMIN.permissions.create_order,
              ],
            },
            {
              href: PAGE_ROUTES.CUSTOMERS_PAGE,
              label: "Customers",
              active: path === PAGE_ROUTES.CUSTOMERS_PAGE,
              icon: User,
              allowedRoles: [
                SALES_OFFICER.role,
                CASHIER.role,
                INVENTORY_MANAGER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                MERCHANDISER.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["customer_profile"],
              allowedPermissions: [
                ...SALES_OFFICER.permissions.customer_profile,
                ...CASHIER.permissions.customer_profile,
                ...INVENTORY_MANAGER.permissions.customer_profile,
                ...PURCHASING_AND_SALES_HEAD.permissions.customer_profile,
                ...EVP.permissions.customer_profile,
                ...MERCHANDISER.permissions.customer_profile,
                ...SUPER_ADMIN.permissions.customer_profile,
              ],
            },
          ],
        },
      ],
    },
    {
      menus: [
        {
          href: PAGE_ROUTES.ORDERS_ALL_ORDERS_PAGE,
          label: "Orders",
          icon: SendToBack,
          allowedRoles: [
            SALES_OFFICER.role,
            CASHIER.role,
            INVENTORY_MANAGER.role,
            INVENTORY_OFFICER.role,
            PURCHASING_AND_SALES_HEAD.role,
            EVP.role,
            SUPER_ADMIN.role,
          ],
          allowedFeatures: ["all_orders", "receive_payment", "create_order"],
          submenus: [
            {
              href: PAGE_ROUTES.ORDERS_ALL_ORDERS_PAGE,
              label: "All Orders",
              active: path === PAGE_ROUTES.ORDERS_ALL_ORDERS_PAGE,
              icon: PackageOpen,
              allowedRoles: [
                SALES_OFFICER.role,
                CASHIER.role,
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["all_orders"],
              allowedPermissions: [
                ...SALES_OFFICER.permissions.all_orders,
                ...CASHIER.permissions.all_orders,
                ...INVENTORY_MANAGER.permissions.all_orders,
                ...INVENTORY_OFFICER.permissions.all_orders,
                ...PURCHASING_AND_SALES_HEAD.permissions.all_orders,
                ...EVP.permissions.all_orders,
                ...SUPER_ADMIN.permissions.all_orders,
              ],
            },
            {
              href: PAGE_ROUTES.ORDERS_ACTIVE_ORDERS_PAGE,
              label: "Active",
              active: path === PAGE_ROUTES.ORDERS_ACTIVE_ORDERS_PAGE,
              icon: Archive,
              allowedRoles: [
                SALES_OFFICER.role,
                CASHIER.role,
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                // PURCHASING_AND_SALES_HEAD.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: [
                "all_orders",
                "receive_payment",
                "create_order",
              ],
              allowedPermissions: [
                ...SALES_OFFICER.permissions.all_orders,
                ...SALES_OFFICER.permissions.create_order,
                ...CASHIER.permissions.all_orders,
                ...CASHIER.permissions.receive_payment,
                ...INVENTORY_MANAGER.permissions.all_orders,
                ...INVENTORY_OFFICER.permissions.all_orders,
                ...PURCHASING_AND_SALES_HEAD.permissions.all_orders,
                ...SUPER_ADMIN.permissions.all_orders,
                ...SUPER_ADMIN.permissions.create_order,
                ...SUPER_ADMIN.permissions.receive_payment,
              ],
            },
            {
              href: PAGE_ROUTES.ORDERS_COMPLETE_ORDERS_PAGE,
              label: "Completed",
              active: path === PAGE_ROUTES.ORDERS_COMPLETE_ORDERS_PAGE,
              icon: Package2,
              allowedRoles: [
                SALES_OFFICER.role,
                CASHIER.role,
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                // PURCHASING_AND_SALES_HEAD.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["all_orders"],
              allowedPermissions: [
                ...SALES_OFFICER.permissions.all_orders,
                ...CASHIER.permissions.all_orders,
                ...INVENTORY_MANAGER.permissions.all_orders,
                ...INVENTORY_OFFICER.permissions.all_orders,
                ...PURCHASING_AND_SALES_HEAD.permissions.all_orders,
                ...SUPER_ADMIN.permissions.all_orders,
              ],
            },
            {
              href: PAGE_ROUTES.ORDERS_CANCELLED_ORDERS_PAGE,
              label: "Cancelled",
              active: path === PAGE_ROUTES.ORDERS_CANCELLED_ORDERS_PAGE,
              icon: ArchiveX,
              allowedRoles: [
                SALES_OFFICER.role,
                CASHIER.role,
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                // PURCHASING_AND_SALES_HEAD.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["all_orders"],
              allowedPermissions: [
                ...SALES_OFFICER.permissions.all_orders,
                ...CASHIER.permissions.all_orders,
                ...INVENTORY_MANAGER.permissions.all_orders,
                ...INVENTORY_OFFICER.permissions.all_orders,
                ...PURCHASING_AND_SALES_HEAD.permissions.all_orders,
                ...SUPER_ADMIN.permissions.all_orders,
              ],
            },
          ],
        },
      ],
    },
    {
      menus: [
        {
          href: PAGE_ROUTES.RETURN_FROM_CUSTOMER_PAGE,
          label: "Returns",
          icon: Undo2,
          allowedRoles: [
            SALES_OFFICER.role,
            INVENTORY_MANAGER.role,
            INVENTORY_OFFICER.role,
            PURCHASING_AND_SALES_HEAD.role,
            MERCHANDISER.role,
            SUPERVISOR.role,
            SUPER_ADMIN.role,
          ],
          allowedFeatures: [
            "return_from_customer",
            "return_to_supplier",
            "customer_profile",
          ],
          submenus: [
            {
              href: PAGE_ROUTES.RETURN_FROM_CUSTOMER_PAGE,
              label: "From Customer",
              active: path === PAGE_ROUTES.RETURN_FROM_CUSTOMER_PAGE,
              icon: ArrowDownToDot,
              allowedRoles: [
                SALES_OFFICER.role,
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                PURCHASING_AND_SALES_HEAD.role,
                MERCHANDISER.role,
                SUPERVISOR.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["return_from_customer", "customer_profile"],
              allowedPermissions: [
                ...SALES_OFFICER.permissions.return_from_customer,
                ...INVENTORY_MANAGER.permissions.return_from_customer,
                ...INVENTORY_MANAGER.permissions.customer_profile,
                ...INVENTORY_OFFICER.permissions.return_from_customer,
                ...PURCHASING_AND_SALES_HEAD.permissions.return_from_customer,
                ...MERCHANDISER.permissions.return_from_customer,
                ...SUPERVISOR.permissions.return_from_customer,
                ...SUPER_ADMIN.permissions.return_from_customer,
              ],
            },
            {
              href: PAGE_ROUTES.RETURN_TO_SUPPLIER_PAGE,
              label: "To Supplier",
              active: path === PAGE_ROUTES.RETURN_TO_SUPPLIER_PAGE,
              icon: ArrowUpFromDot,
              allowedRoles: [
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                PURCHASING_AND_SALES_HEAD.role,
                MERCHANDISER.role,
                SUPERVISOR.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["return_to_supplier", "customer_profile"],
              allowedPermissions: [
                ...INVENTORY_MANAGER.permissions.return_to_supplier,
                ...INVENTORY_MANAGER.permissions.customer_profile,
                ...INVENTORY_OFFICER.permissions.return_to_supplier,
                ...PURCHASING_AND_SALES_HEAD.permissions.return_to_supplier,
                ...MERCHANDISER.permissions.return_to_supplier,
                ...SUPERVISOR.permissions.return_to_supplier,
                ...SUPER_ADMIN.permissions.return_to_supplier,
              ],
            },
          ],
        },
      ],
    },
    {
      menus: [
        {
          href: PAGE_ROUTES.ITEMS_INVENTORY_PAGE,
          label: "Items",
          icon: StretchHorizontal,
          allowedRoles: [
            SALES_OFFICER.role,
            CASHIER.role,
            INVENTORY_MANAGER.role,
            INVENTORY_OFFICER.role,
            PURCHASING_AND_SALES_HEAD.role,
            EVP.role,
            SUPERVISOR.role,
            MERCHANDISER.role,
            SUPER_ADMIN.role,
          ],
          allowedFeatures: [
            "inventory",
            "inventory_reports",
            "price_and_discount",
            "stock_in",
            "stock_transfer",
            "reports_and_analytics",
            "item_management",
            "return_to_supplier",
          ],
          submenus: [
            {
              href: PAGE_ROUTES.ITEMS_INVENTORY_PAGE,
              label: "Inventory",
              active: path === PAGE_ROUTES.ITEMS_INVENTORY_PAGE,
              icon: Package,
              allowedRoles: [
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                SUPERVISOR.role,
                MERCHANDISER.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["inventory"],
              allowedPermissions: [
                ...INVENTORY_MANAGER.permissions.inventory,
                ...INVENTORY_OFFICER.permissions.inventory,
                ...PURCHASING_AND_SALES_HEAD.permissions.inventory,
                ...EVP.permissions.inventory,
                ...MERCHANDISER.permissions.inventory,
                ...SUPER_ADMIN.permissions.inventory,
                ...SUPERVISOR.permissions.inventory,
              ],
            },
            {
              href: PAGE_ROUTES.ITEMS_PRICE,
              label: "Price",
              active: path === PAGE_ROUTES.ITEMS_PRICE,
              icon: PhilippinePeso,
              allowedRoles: [
                CASHIER.role,
                INVENTORY_MANAGER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                MERCHANDISER.role,
                SUPERVISOR.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["price_and_discount"],
              allowedPermissions: [
                ...CASHIER.permissions.price_and_discount,
                ...INVENTORY_MANAGER.permissions.price_and_discount,
                ...PURCHASING_AND_SALES_HEAD.permissions.price_and_discount,
                ...EVP.permissions.price_and_discount,
                ...MERCHANDISER.permissions.price_and_discount,
                ...SUPER_ADMIN.permissions.price_and_discount,
                ...SUPERVISOR.permissions.price_and_discount,
              ],
            },
            {
              href: PAGE_ROUTES.ITEMS_STOCK_IN_PAGE,
              label: "Stock In",
              active: path === PAGE_ROUTES.ITEMS_STOCK_IN_PAGE,
              icon: ArchiveRestore,
              allowedRoles: [
                INVENTORY_MANAGER.role,
                PURCHASING_AND_SALES_HEAD.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["stock_in"],
              allowedPermissions: [
                ...INVENTORY_MANAGER.permissions.stock_in,
                ...PURCHASING_AND_SALES_HEAD.permissions.stock_in,
                ...SUPER_ADMIN.permissions.stock_in,
              ],
            },
            {
              href: PAGE_ROUTES.ITEMS_STOCK_TRANSFER_PAGE,
              label: "Stock Transfer",
              active: path === PAGE_ROUTES.ITEMS_STOCK_TRANSFER_PAGE,
              icon: ArrowsUpFromLine,
              allowedRoles: [
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["stock_transfer"],
              allowedPermissions: [
                ...INVENTORY_MANAGER.permissions.stock_transfer,
                ...INVENTORY_OFFICER.permissions.stock_transfer,
                ...SUPER_ADMIN.permissions.stock_transfer,
              ],
            },
            {
              href: PAGE_ROUTES.ITEMS_STOCK_ADJUSTMENT_PAGE,
              label: "Stock Adjustment",
              active: path === PAGE_ROUTES.ITEMS_STOCK_ADJUSTMENT_PAGE,
              icon: Ratio,
              allowedRoles: [
                INVENTORY_MANAGER.role,
                SUPER_ADMIN.role,
                SUPERVISOR.role,
                EVP.role,
                INVENTORY_OFFICER.role,
              ],
              allowedFeatures: ["item_management"],
              allowedPermissions: [
                ...INVENTORY_MANAGER.permissions.item_management,
                ...SUPER_ADMIN.permissions.item_management,
                ...SUPERVISOR.permissions.item_management,
                ...EVP.permissions.item_management,
                ...INVENTORY_OFFICER.permissions.item_management,
              ],
            },
            {
              href: PAGE_ROUTES.ITEMS_SOLD_PAGE,
              label: "Sold",
              active: path === PAGE_ROUTES.ITEMS_SOLD_PAGE,
              icon: ShoppingBag,
              allowedRoles: [
                INVENTORY_MANAGER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                MERCHANDISER.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["inventory_reports"],
              allowedPermissions: [
                ...INVENTORY_MANAGER.permissions.inventory_reports,
                ...PURCHASING_AND_SALES_HEAD.permissions.inventory_reports,
                ...EVP.permissions.inventory_reports,
                ...MERCHANDISER.permissions.inventory_reports,
                ...SUPER_ADMIN.permissions.inventory_reports,
              ],
            },
            {
              href: PAGE_ROUTES.ITEMS_ITEM_PAGE,
              label: "Item",
              active: path === PAGE_ROUTES.ITEMS_ITEM_PAGE,
              icon: PackageSearch,
              allowedRoles: [
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                MERCHANDISER.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["item_management"],
              allowedPermissions: [
                ...INVENTORY_MANAGER.permissions.item_management,
                ...INVENTORY_OFFICER.permissions.item_management,
                ...PURCHASING_AND_SALES_HEAD.permissions.item_management,
                ...EVP.permissions.item_management,
                ...MERCHANDISER.permissions.item_management,
                ...SUPER_ADMIN.permissions.item_management,
              ],
            },
            {
              href: PAGE_ROUTES.ITEMS_CATEGORY_PAGE,
              label: "Categories",
              active: path === PAGE_ROUTES.ITEMS_CATEGORY_PAGE,
              icon: Ungroup,
              allowedRoles: [
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                MERCHANDISER.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["item_management"],
              allowedPermissions: [
                ...INVENTORY_MANAGER.permissions.item_management,
                ...INVENTORY_OFFICER.permissions.item_management,
                ...PURCHASING_AND_SALES_HEAD.permissions.item_management,
                ...EVP.permissions.item_management,
                ...MERCHANDISER.permissions.item_management,
                ...SUPER_ADMIN.permissions.item_management,
              ],
            },
            {
              href: PAGE_ROUTES.ITEM_UNIT_OF_MEASURE,
              label: "Unit of Measure",
              active: path === PAGE_ROUTES.ITEM_UNIT_OF_MEASURE,
              icon: Ruler,
              allowedRoles: [
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                MERCHANDISER.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["item_management"],
              allowedPermissions: [
                ...INVENTORY_MANAGER.permissions.item_management,
                ...INVENTORY_OFFICER.permissions.item_management,
                ...PURCHASING_AND_SALES_HEAD.permissions.item_management,
                ...EVP.permissions.item_management,
                ...MERCHANDISER.permissions.item_management,
                ...SUPER_ADMIN.permissions.item_management,
              ],
            },
            {
              href: PAGE_ROUTES.ITEM_SUPPLIER,
              label: "Supplier",
              active: path === PAGE_ROUTES.ITEM_SUPPLIER,
              icon: Container,
              allowedRoles: [
                INVENTORY_MANAGER.role,
                INVENTORY_OFFICER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                MERCHANDISER.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["return_to_supplier"],
              allowedPermissions: [
                ...INVENTORY_MANAGER.permissions.return_to_supplier,
                ...INVENTORY_OFFICER.permissions.return_to_supplier,
                ...PURCHASING_AND_SALES_HEAD.permissions.return_to_supplier,
                ...EVP.permissions.return_to_supplier,
                ...MERCHANDISER.permissions.return_to_supplier,
                ...SUPER_ADMIN.permissions.return_to_supplier,
              ],
            },
          ],
        },
      ],
    },
    {
      menus: [
        {
          href: PAGE_ROUTES.OPERATIONS_STOCK_LOCATIONS_PAGE,
          label: "Operations",
          icon: GroupOperations,
          allowedRoles: [
            INVENTORY_MANAGER.role,
            MERCHANDISER.role,
            PURCHASING_AND_SALES_HEAD.role,
            CASHIER.role,
            ADMINISTRATOR.role,
            EVP.role,
            SUPER_ADMIN.role,
            SALES_OFFICER.role,
          ],
          allowedFeatures: [
            "tenant_management",
            "price_and_discount",
            "override_order_wholesale_discount",
            "item_wholesale_discount",
          ],
          submenus: [
            {
              href: PAGE_ROUTES.OPERATIONS_STOCK_LOCATIONS_PAGE,
              label: "Stock Locations",
              active: path === PAGE_ROUTES.OPERATIONS_STOCK_LOCATIONS_PAGE,
              icon: BaggageClaim,
              allowedRoles: [
                ADMINISTRATOR.role,
                EVP.role,
                MERCHANDISER.role,
                PURCHASING_AND_SALES_HEAD.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["tenant_management"],
              allowedPermissions: [
                ...PURCHASING_AND_SALES_HEAD.permissions.tenant_management,
                ...ADMINISTRATOR.permissions.tenant_management,
                ...EVP.permissions.tenant_management,
                ...MERCHANDISER.permissions.tenant_management,
                ...SUPER_ADMIN.permissions.tenant_management,
              ],
            },
            {
              href: PAGE_ROUTES.OPERATIONS_PAYMENT_METHOD_PAGE,
              label: "Payment Method",
              active: path === PAGE_ROUTES.OPERATIONS_PAYMENT_METHOD_PAGE,
              icon: CreditCard,
              allowedRoles: [
                MERCHANDISER.role,
                EVP.role,
                PURCHASING_AND_SALES_HEAD.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: [
                "price_and_discount",
                "override_order_wholesale_discount",
                "item_wholesale_discount",
              ],
              allowedPermissions: [
                ...MERCHANDISER.permissions.price_and_discount,
                ...MERCHANDISER.permissions.override_order_wholesale_discount,
                ...MERCHANDISER.permissions.item_wholesale_discount,
                ...EVP.permissions.price_and_discount,
                ...EVP.permissions.item_wholesale_discount,
                ...EVP.permissions.override_order_wholesale_discount,
                ...PURCHASING_AND_SALES_HEAD.permissions.price_and_discount,
                ...PURCHASING_AND_SALES_HEAD.permissions
                  .item_wholesale_discount,
                ...PURCHASING_AND_SALES_HEAD.permissions
                  .override_order_wholesale_discount,
                ...SUPER_ADMIN.permissions.price_and_discount,
                ...SUPER_ADMIN.permissions.override_order_wholesale_discount,
                ...SUPER_ADMIN.permissions.item_wholesale_discount,
              ],
            },
            {
              href: PAGE_ROUTES.OPERATIONS_VOID_PAGE,
              label: "Void",
              active: path === PAGE_ROUTES.OPERATIONS_VOID_PAGE,
              icon: CircleSlash,
              allowedRoles: [
                MERCHANDISER.role,
                EVP.role,
                SUPER_ADMIN.role,
                PURCHASING_AND_SALES_HEAD.role,
              ],
              allowedFeatures: [
                "price_and_discount",
                "override_order_wholesale_discount",
                "item_wholesale_discount",
              ],
              allowedPermissions: [
                ...MERCHANDISER.permissions.price_and_discount,
                ...MERCHANDISER.permissions.override_order_wholesale_discount,
                ...MERCHANDISER.permissions.item_wholesale_discount,
                ...EVP.permissions.price_and_discount,
                ...EVP.permissions.item_wholesale_discount,
                ...EVP.permissions.override_order_wholesale_discount,
                ...SUPER_ADMIN.permissions.price_and_discount,
                ...SUPER_ADMIN.permissions.override_order_wholesale_discount,
                ...SUPER_ADMIN.permissions.item_wholesale_discount,
                ...PURCHASING_AND_SALES_HEAD.permissions.price_and_discount,
              ],
            },
            {
              href: PAGE_ROUTES.OPERATIONS_VOUCHERS_PAGE,
              label: "Vouchers",
              active: path === PAGE_ROUTES.OPERATIONS_VOUCHERS_PAGE,
              icon: Gift,
              allowedRoles: [
                MERCHANDISER.role,
                EVP.role,
                SUPER_ADMIN.role,
                SALES_OFFICER.role,
                PURCHASING_AND_SALES_HEAD.role,
              ],
              allowedFeatures: [
                "price_and_discount",
                "override_order_wholesale_discount",
                "item_wholesale_discount",
              ],
              allowedPermissions: [
                ...MERCHANDISER.permissions.price_and_discount,
                ...MERCHANDISER.permissions.override_order_wholesale_discount,
                ...MERCHANDISER.permissions.item_wholesale_discount,
                ...EVP.permissions.price_and_discount,
                ...EVP.permissions.item_wholesale_discount,
                ...EVP.permissions.override_order_wholesale_discount,
                ...SUPER_ADMIN.permissions.price_and_discount,
                ...SUPER_ADMIN.permissions.override_order_wholesale_discount,
                ...SUPER_ADMIN.permissions.item_wholesale_discount,
                ...SALES_OFFICER.permissions.price_and_discount,
                ...PURCHASING_AND_SALES_HEAD.permissions.price_and_discount,
              ],
            },
            {
              href: PAGE_ROUTES.OPERATIONS_DISCOUNTS_PAGE,
              label: "Discount",
              active: path === PAGE_ROUTES.OPERATIONS_DISCOUNTS_PAGE,
              icon: BadgePercent,
              allowedRoles: [
                MERCHANDISER.role,
                CASHIER.role,
                EVP.role,
                SUPER_ADMIN.role,
                SALES_OFFICER.role,
                PURCHASING_AND_SALES_HEAD.role,
              ],
              allowedFeatures: [
                "price_and_discount",
                "override_order_wholesale_discount",
                "item_wholesale_discount",
              ],
              allowedPermissions: [
                ...MERCHANDISER.permissions.price_and_discount,
                ...MERCHANDISER.permissions.override_order_wholesale_discount,
                ...MERCHANDISER.permissions.item_wholesale_discount,
                ...CASHIER.permissions.price_and_discount,
                ...EVP.permissions.price_and_discount,
                ...EVP.permissions.item_wholesale_discount,
                ...EVP.permissions.override_order_wholesale_discount,
                ...SUPER_ADMIN.permissions.price_and_discount,
                ...SUPER_ADMIN.permissions.override_order_wholesale_discount,
                ...SUPER_ADMIN.permissions.item_wholesale_discount,
                ...SALES_OFFICER.permissions.price_and_discount,
                ...PURCHASING_AND_SALES_HEAD.permissions.price_and_discount,
              ],
            },
          ],
        },
      ],
    },
    {
      menus: [
        {
          href: PAGE_ROUTES.REPORTS_PRICE_REPORT_PAGE,
          label: "Reports",
          icon: ClipboardPlus,
          allowedRoles: [
            CASHIER.role,
            PURCHASING_AND_SALES_HEAD.role,
            EVP.role,
            MERCHANDISER.role,
            SUPER_ADMIN.role,
          ],
          allowedFeatures: ["price_analysis_report", "reports_and_analytics"],
          submenus: [
            {
              href: PAGE_ROUTES.REPORTS_PRICE_REPORT_PAGE,
              label: "Prices",
              active: path === PAGE_ROUTES.REPORTS_PRICE_REPORT_PAGE,
              icon: SquarePercent,
              allowedRoles: [
                CASHIER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                MERCHANDISER.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["price_analysis_report"],
              allowedPermissions: [
                ...CASHIER.permissions.price_analysis_report,
                ...PURCHASING_AND_SALES_HEAD.permissions.price_analysis_report,
                ...EVP.permissions.price_analysis_report,
                ...MERCHANDISER.permissions.price_analysis_report,
                ...SUPER_ADMIN.permissions.price_analysis_report,
              ],
            },
            {
              href: PAGE_ROUTES.REPORTS_SALES_REPORT_PAGE,
              label: "Sales",
              active: path === PAGE_ROUTES.REPORTS_SALES_REPORT_PAGE,
              icon: Wallet,
              allowedRoles: [
                CASHIER.role,
                PURCHASING_AND_SALES_HEAD.role,
                EVP.role,
                MERCHANDISER.role,
                SUPER_ADMIN.role,
              ],
              allowedFeatures: ["reports_and_analytics"],
              allowedPermissions: [
                ...CASHIER.permissions.reports_and_analytics,
                ...PURCHASING_AND_SALES_HEAD.permissions.reports_and_analytics,
                ...EVP.permissions.reports_and_analytics,
                ...MERCHANDISER.permissions.reports_and_analytics,
                ...SUPER_ADMIN.permissions.reports_and_analytics,
              ],
            },
          ],
        },
      ],
    },
    {
      menus: [
        {
          href: PAGE_ROUTES.USERS_PAGE,
          label: "Settings",
          icon: Cog,
          allowedRoles: [ADMINISTRATOR.role, SUPER_ADMIN.role],
          allowedFeatures: [
            "user_management",
            "user_access_management",
            "api_key_management",
          ],
          submenus: [
            {
              href: PAGE_ROUTES.USERS_PAGE,
              label: "Users",
              active: path === PAGE_ROUTES.USERS_PAGE,
              icon: Users2Icon,
              allowedRoles: [ADMINISTRATOR.role, SUPER_ADMIN.role],
              allowedFeatures: ["user_management"],
              allowedPermissions: [
                ...ADMINISTRATOR.permissions.user_management,
                ...SUPER_ADMIN.permissions.user_management,
              ],
            },
            {
              href: PAGE_ROUTES.ACTIVITY_LOG_PAGE,
              label: "Activity Logs",
              active: path === PAGE_ROUTES.ACTIVITY_LOG_PAGE,
              icon: ActivityIcon,
              allowedRoles: [ADMINISTRATOR.role, SUPER_ADMIN.role],
              allowedFeatures: ["user_access_management"],
              allowedPermissions: [
                ...ADMINISTRATOR.permissions.user_access_management,
                ...SUPER_ADMIN.permissions.user_access_management,
              ],
            },
            {
              href: PAGE_ROUTES.INTEGRATION_APPS_PAGE,
              label: "Integration",
              active: path === PAGE_ROUTES.INTEGRATION_APPS_PAGE,
              icon: GitPullRequestCreateArrow,
              allowedRoles: [ADMINISTRATOR.role, SUPER_ADMIN.role],
              allowedFeatures: ["api_key_management"],
              allowedPermissions: [
                ...ADMINISTRATOR.permissions.api_key_management,
                ...SUPER_ADMIN.permissions.api_key_management,
              ],
            },
          ],
        },
      ],
    },
  ]
}
